[[redirects]]
    from = "https://www.yadavhimanshu.com/*"
    to = "https://www.ihimanshu.in/"
    status = 301
    force = true
[[redirects]]
    from = "https://ihimanshu.in/*"
    to = "https://www.ihimanshu.in/"
    status = 301
    force = true

[[headers]]
    for = "/assets/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
    for = "/css/*"
    [headers.values]
        Cache-Control = "public, max-age=604800"

[[headers]]
    for = "/js/*"
    [headers.values]
        Cache-Control = "public, max-age=604800"